### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by nokfert** [shiwer/ear-training-obsidian-plugin#2]
After clicking Install button in Obsidian receiving an error message:
Failed to install plugin "Ear Training"

**Comment by dev-araujo** [comment]
I had same problem :(

**Comment by SathyaPriya1916** [comment]
Facing the same problem!

**Comment by DanShui-Yu** [comment]
+1

**Comment by shiwer** [comment]
My bad, I forgot the binaries on the last release. I need to fix the action release script so this doesn't happen in the futur.
